name: healthy-eating
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51824
title: eat healthy live longer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe5c5c'
    - '#530000'
    - '#ba0000'
    - '#fe3939'
    - '#fe8484'
  brandStrength: 0.0625
  lightness: 0.9375
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
