name: healthy-eating
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#180a09'
    - '#693915'
    - '#ff8538'
    - '#de4837'
    - '#fffaf8'
  brandStrength: 0.5625
  lightness: 0.9375
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
