name: healthy-eating
favicon: null
layout_spectrum: 0.4814
typography_spectrum: 0.51824
title: 'eat healthy, live longer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76197069-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a50021'
    - '#f57856'
    - '#000000'
    - '#7f7f7f'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
